/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "os_common.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_SizeZeroError_osCirBufCreate(void);
extern void test_CBNullError_osCirBufCreate(void);
extern void test_BufferNullError_osCirBufCreate(void);
extern void test_isWorking_osCirBufCreate(void);
extern void test_CheckInitVariables_osCirBufCreate(void);
extern void test_PointerNullError_osCirBufClear(void);
extern void test_BufferNullError_osCirBufClear(void);
extern void test_BufferSizeZeroError_osCirBufClear(void);

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestOsCirBuff.c");
  //
  RUN_TEST(test_SizeZeroError_osCirBufCreate, __LINE__);
  RUN_TEST(test_CBNullError_osCirBufCreate, __LINE__);
  RUN_TEST(test_BufferNullError_osCirBufCreate, __LINE__);
  RUN_TEST(test_isWorking_osCirBufCreate, __LINE__);
  RUN_TEST(test_CheckInitVariables_osCirBufCreate, __LINE__);
  //
  RUN_TEST(test_PointerNullError_osCirBufClear, __LINE__);
  RUN_TEST(test_BufferNullError_osCirBufClear, __LINE__);
  RUN_TEST(test_BufferSizeZeroError_osCirBufClear, __LINE__);
  //


  return (UnityEnd());
}
